### PR TITLE
🐛  Trying to fix an issue with GINKGO

### PR DESCRIPTION
**Pull request by ponytojas**
Related to this post
https://discuss.openedx.org/t/runtimeerror-while-installing-figures-on-ironwood/4000

I just check that trying to install and use 0.4 is not working on Ginkgo.master release

Found the following runtime error:

> RuntimeError: Conflicting 'studentmodule' models in application 'courseware': <class 'courseware.models.StudentModule'> and <class 'lms.djangoapps.courseware.models.StudentModule'>.

Tried the model change name fix on my fork and everything seems to be working.

### CODE REVIEW

**Comment by johnbaldwin** [comment]
Hi @ponytojas , thanks for posting this PR. The link to the discussion post is on getting Figures to run in Ironwood. You're trying to get it to work on Ginkgo, right?

**Comment by ponytojas** [comment]
Yes that's right, I'm making it works on Ginkgo.

The discussion post just point to me what to try.

**Review by bryanlandia — COMMENTED** [review]
Thanks @ponytojas 
Looks good @johnbaldwin though I think we want `lms.djangoapps.courseware` everywhere below Ginkgo, actually.
And the PR would need to be rebased off of current head of master branch, and conflicts resolved, too.

**Comment by OmarIthawi** [comment]
@ponytojas thanks for posting this pull request. Do you still have time to follow up with the changes you posted?

**Comment by OmarIthawi** [comment]
Thanks @ponytojas for the update and I best wishes for you in your new company.

I'll cherry-pick your fixes and close this PR.

**Comment by OmarIthawi** [comment]
@johnbaldwin tests seems to run now, please merge either this or the newer #423 PR.

Thanks again @ponytojas.

**Comment by johnbaldwin** [comment]
Sorry this has been hanging out so long. Thanks for posting a new PR with the current code, @OmarIthawi  in this PR: https://github.com/appsembler/figures/pull/423
I approved #423 , so feel free to close this one

**Comment by OmarIthawi** [comment]
Thanks again @ponytojas, I've cherry picked your changed and now it's merged into `main`.

I'm closing this pull request.

**Pull request closed without merging**
