### PR TITLE
DLRepots UI - Add Download Reports to frontend

### PR DESCRIPTION
**Pull request by johnbaldwin**
This PR supercedes PR #118 

Cherry picked the commits from branch `matej-work/add-autogenerated-csv-reports`, keeping only the `frontend/src` files (removing the updates to `figures/static` and `figures/webpack-stats.json`)

This requires Appsembler Reporting DLReports CSV API endpoint, so we cannot merge to master until one of the two conditions happen

1. We feature flag the DLReports UI so we can conditionally show/hide it
or
2. Appsembler Reporting is installed on Tahoe and all Enterprise prod servers running figures

### CODE REVIEW

**Comment by johnbaldwin** [comment]
Travis appears to be failing on the build but I can build locally when I do a fresh workspace. See the console output below.

Also, I can't seem to find any docs to find where `home` is in order to read the NPM log file and I've tried different paths to see if `/home` is off of figures or the root. No Joy.


```
33.67s$ cd frontend && npm run-script build && cd ..
534
535> frontend@0.1.0 build /home/travis/build/appsembler/figures/frontend
536> node scripts/build.js
537
538Creating an optimized production build...
539
540Treating warnings as errors because process.env.CI = true.
541Most CI servers set it automatically.
542
543Failed to compile.
544
545./src/views/CsvReports.js
546  Line 8:  'apiConfig' is defined but never used  no-unused-vars
547
548
549npm ERR! code ELIFECYCLE
550npm ERR! errno 1
551npm ERR! frontend@0.1.0 build: `node scripts/build.js`
552npm ERR! Exit status 1
553npm ERR! 
554npm ERR! Failed at the frontend@0.1.0 build script.
555npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
556
557npm ERR! A complete log of this run can be found in:
558npm ERR!     /home/travis/.npm/_logs/2019-12-04T03_23_12_457Z-debug.log
559The command "cd frontend && npm run-script build && cd .." exited with 1.
```

**Comment by johnbaldwin** [comment]
@grozdanowski Do you have any insight into what could be failing for the front end?

**Comment by johnbaldwin** [comment]
Confirmed it is a front end build issue from this PR: https://github.com/appsembler/figures/pull/148

Investigating...

**Comment by grozdanowski** [comment]
@johnbaldwin I made a change and now I see travis builds successfully passing.
The error you pasted was saying it all :)
In the file`CsvReports.js` we had `apiConfig` imported but never used. This usually triggers just a minor warning, however, as your log notes - `Treating warnings as errors because process.env.CI = true.` which means any minor warning will throw an error. Which is not a super big issue, but rather something I should know (and now know) in order to make sure no warnings whatsoever (even super minor ones) slip into our codebase.

**Comment by johnbaldwin** [comment]
@grozdanowski This is now good to go. However, we still can't incorporate the code into master until we feature flag it as we need to ensure DLReports properly protects PII before deploying to production

cc @abeals

**Comment by johnbaldwin** [comment]
Oh, and sorry, Thanks for fixing this @grozdanowski !

**Comment by grozdanowski** [comment]
@johnbaldwin I think my latest commits resolved the issue of flagging the feature. Essentially, what I added was an ENV variable that conditions whether that interface is displayed, as well as whether the API fetches are attempted to get the CSV data. Also added a catchall in the router so if someone attempts any non-enabled URL it just reroutes to the Figures root (Dashboard).

So, by default the CSV Reports feature is disabled. So if you run:
`yarn build`
the app will build with CSV Reports disabled.

If you want the app to have the feature enabled, when running the build locally or on server just run:
`ENABLE_CSV_REPORTS=enabled yarn build`
and the feature is there.

**Comment by johnbaldwin** [comment]
Thanks @grozdanowski I'll merge in the two new PRs #153 #154 then merge master to this and double check in devsite, then merge to master if I don't see the DLReports UI

**Comment by johnbaldwin** [comment]
@grozdanowski The front end build is failing after we merged master into this branch

Please see here https://travis-ci.org/appsembler/figures/jobs/628888072?utm_medium=notification&utm_source=github_status


```
$ cd frontend && npm run-script build && cd ..
526
527> frontend@0.1.0 build /home/travis/build/appsembler/figures/frontend
528> node scripts/build.js
529
530Creating an optimized production build...
531Failed to compile.
532
533./src/redux/actions/Actions.js
534  Line 146:  'addActiveApiFetch' is not defined     no-undef
535  Line 150:  'removeActiveApiFetch' is not defined  no-undef
536  Line 162:  'addActiveApiFetch' is not defined     no-undef
537  Line 166:  'removeActiveApiFetch' is not defined  no-undef
538  Line 178:  'addActiveApiFetch' is not defined     no-undef
539  Line 182:  'removeActiveApiFetch' is not defined  no-undef
```

**Comment by johnbaldwin** [comment]
@grozdanowski I just restarted the TravisCI build and the front-end build fails with the same error I reported above (https://github.com/appsembler/figures/pull/146#issuecomment-568712583)

**Comment by grozdanowski** [comment]
@johnbaldwin I just checked and made a commit that fixes the issue you were getting.

**Pull request merged**
