### PR TITLE
Fix CourseEnrollment display 'leakage' betwen Sites

### PR DESCRIPTION
**Pull request by bryanlandia**
## Change description

Limit display of CourseEnrollments to requested Site in cases where users have enrollments for courses in more than one Site

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

fix https://github.com/appsembler/figures/issues/392

### Development

- [ ] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

### CODE REVIEW

**Comment by bryanlandia** [comment]
So far this just adds a breaking test to confirm the bug.

**Comment by bryanlandia** [comment]
Fix is in place and tested now.  Ready for review.

**Comment by bryanlandia** [comment]
```
tests/test_sites.py::TestHandlersForMultisiteMode::test_get_course_enrollments_for_site_exclude_same_user_different_site PASSED                               [ 62%]
```

**Comment by bryanlandia** [comment]
Moving some info from Slack thread to here

Adding the additional filter indeed adds one query to the `get_course_enrollments_for_site` function

Queries:
========

```
SELECT "organizations_organizationcourse"."course_id" FROM "organizations_organizationcourse" INNER JOIN "organizations_organization" ON ("organizations_organizationcourse"."organization_id" = "organizations_organization"."id") INNER JOIN "organizations_organization_sites" ON ("organizations_organization"."id" = "organizations_organization_sites"."organization_id") WHERE "organizations_organization_sites"."site_id" IN (2)

SELECT "student_courseenrollment"."id", "student_courseenrollment"."user_id", "student_courseenrollment"."course_id", "student_courseenrollment"."created", "student_courseenrollment"."is_active", "student_courseenrollment"."mode" FROM "student_courseenrollment" INNER JOIN "auth_user" ON ("student_courseenrollment"."user_id" = "auth_user"."id") INNER JOIN "organizations_userorganizationmapping" ON ("auth_user"."id" = "organizations_userorganizationmapping"."user_id") INNER JOIN "organizations_organization" ON ("organizations_userorganizationmapping"."organization_id" = "organizations_organization"."id") INNER JOIN "organizations_organization_sites" ON ("organizations_organization"."id" = "organizations_organization_sites"."organization_id") WHERE ("student_courseenrollment"."course_id" IN ('course-v1:StarFleetAcademy+SFA18+2161') AND "organizations_organization_sites"."site_id" IN (2)) ORDER BY "student_courseenrollment"."user_id" ASC, "student_courseenrollment"."course_id" ASC
```


Looks like the method is called from

* `metrics.get_total_site_courses_for_time_period` but only if `calc_raw` kwarg is used… which it never seems to be
* `serializers.LearnerDetailsSerializer` which is the case we were correcting for, with the queries listed above
* `views.CourseEnrollmentViewSet`  db queries for test/views/test_coursenrollment_view.py went from 11 to 12 for multisite, using new filter
`backfill.backfill_enrollment_data` which will add have one additional query for whole backfill

**Comment by johnbaldwin** [comment]
So, just recapping from our Slack chat @bryanlandia 

I did some rough performance testing by running a script in the Django shell with a number of our customers including our largest customers (by course and course enrollment counts) and there's a small overhead that adds less than 0.1 second cost to the query (Caveat, this was in the Django shell). Given the effort to reduce this cost, I think it is reasonable to move forward with this fix, but Omar should review it since unless the query is a configurable setting, it will be running in Tahoe

Ref link: https://appsembler.slack.com/archives/C1L469CFN/p1628187008012300

**Comment by bryanlandia** [comment]
From @johnbaldwin 's performance exploration

Py script to log exec time for function options 
https://gist.github.com/bryanlandia/f600245a86ed5a30f5b6ae1bab1da9de

> Here's the output running original, then the new option:

```
>>> exec(open("/home/john/ce_query.py").read())
>>> test_all_original()
testing cyberreason
enrollment_count=32971
2021-08-06 21:25:38,086 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [81]:cybereason.tahoe.appsembler.com: 0.12435447052121162 s
testing chef
enrollment_count=18553
2021-08-06 21:25:38,171 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [2142]:learn.chef.io: 0.08445320650935173 s
testing jeanologia
enrollment_count=594
2021-08-06 21:25:38,179 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [1353]:jeanologia.tahoe.appsembler.com: 0.007444966584444046 s
testing realnetworks
enrollment_count=1980
2021-08-06 21:25:38,189 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [2288]:realnetworks.tahoe.appsembler.com: 0.009611252695322037 s
testing redis_labs
enrollment_count=55365
2021-08-06 21:25:38,436 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [535]:university.redislabs.com: 0.24689404107630253 s
testing amplify
enrollment_count=10656
2021-08-06 21:25:38,518 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [817]:pd.amplify.com: 0.0810097549110651 s
>>>
>>> test_all_option1()
testing cyberreason
enrollment_count=32971
2021-08-06 21:26:23,260 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [81]:cybereason.tahoe.appsembler.com: 0.1221456341445446 s
testing chef
enrollment_count=18553
2021-08-06 21:26:23,356 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [2142]:learn.chef.io: 0.09614074230194092 s
testing jeanologia
enrollment_count=594
2021-08-06 21:26:23,365 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [1353]:jeanologia.tahoe.appsembler.com: 0.007950715720653534 s
testing realnetworks
enrollment_count=1980
2021-08-06 21:26:23,376 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [2288]:realnetworks.tahoe.appsembler.com: 0.01053665392100811 s
testing redis_labs
enrollment_count=55365
2021-08-06 21:26:23,665 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [535]:university.redislabs.com: 0.2891354728490114 s
testing amplify
enrollment_count=10656
2021-08-06 21:26:23,761 INFO 14934 [figures.log] [user None] log.py:38 - Ran option1. [817]:pd.amplify.com: 0.09486442804336548 s
```

> It's starting to push the envelop with Cybereason and RedisLabs, but next I'll add a test for the "before" to see if there's any real extra cost...

> There's a small overhead for the new query, most pronounced in the bigger sites, which makes sense. It's not a big overhead. This is almost certainly not going to show up as an issue on Tahoe staging as the data sets are too small. I believe it will only show up as an issue on Tahoe prod for Redis first, since the query takes the most time there and only if that extra fraction of a second is a straw that breaks the camel's back for a request timeout.

> I'm just particularly sensitive to query performance issues in Figures API because we've got some slow behavior for site monthly metrics responding to the UI that needs to be addressed, it's a UX issue. Slow UI sucks

**Comment by bryanlandia** [comment]
@OmarIthawi would you be able to look this over from the standpoint of Tahoe performance?  John suggested you review.

**Comment by bryanlandia** [comment]
My take is that the 0.04 additional seconds for a larger site like Redis Labs is not a big deal.

**Comment by OmarIthawi** [comment]
> Limit display of CourseEnrollments to requested Site in cases where users have enrollments for courses in more than one Site

@bryanlandia Would you mind sharing why we're doing this change? It seems like a bug in Tahoe data which we should clean.

If it's to support Tahoe Enterprise work, then I think we're bending Figures in a way that it's not really supposed to work: support multi-site but the same user can login across multiple sites.

If it's a single-customer requirement, then I think it's fair to ask for a Figure fork branch or pluggable query (may not be worth it) to support this special case.

Figures is both a core product of Tahoe and a community tool, which we should be a little bit careful of what we add to it and avoid introducing customer-specific logic whenever possible.

**Comment by johnbaldwin** [comment]
Following Omar's comment...

This PR is a result of the fact that in Tahoe, a user cannot be a member of more than one site. Open edX (or any Django multi-tenant environment really) doesn't have to have unique per-site users. Also Tahoe is currently the only multi-tenant environment Figures supports because, well, that's the only multi-tenant platform **we** have needed to support to date. We have an enterprise customer whose existing model is being able to have a user belong to multiple sites. So now we have another need and managing a fork for this PR to support an existing (and long standing) customer is not tractable.

One could argue that if we had deployed Figures to this customer first, then deployed to Tahoe, we would not be having this PR or conversation.

So to me it is not a matter of if we incorporate this filtering, but how. To note, this PR imposes a fractional performance hit to the enrollments query used by the API. This is not ideal, we don't want to incur additional performance debt on Figures API. However the cost does appear quite small.

Therefore, I see three basic ways to add this "user can belong to multiple sites" enrollment filtering

1. We accept the PR and its fractional additional performance overhead
2. We use a "server-vars" setting to conditionally execute the logic
3. We build on the existing "sites backend" concept to have Figures be able to operate on different backends, such as "single site backend", "Tahoe multi-site backend", "Enterprise X backend", and that leaves it open for community members who run their own multi-tenant Open edX to use their own backend

My preference her is to iterate through each of these. We go with option 1 for now, which is what this PR does. If we see there's an unacceptable performance hit, we implement option 2, unless we've already implemented option 3, which is something we're either going to want to do or be compelled to do anyway as we improve and evolve Figurews

**Comment by bryanlandia** [comment]
Thanks @johnbaldwin and @OmarIthawi .  Yeah, I feel pretty strongly that what the PR addresses is not the special case, so much as Tahoe is a special case.  I don't see this as a customer-specific change and if we do need a platform-specific setting the default should not be Tahoe's behavior/restriction.  

I need to make a decision either way today-ish so I can update for NYIF.

**Review by OmarIthawi — APPROVED** [review]
Thanks @bryanlandia and John for the additional details. I don't have a strong push against this PR as it looks pretty much benign. Please feel free to merge it.

~I'll follow up with a comment that shouldn't affect the status of this PR.~

**Pull request merged**
