### PR TITLE
Build 0.3.9

### PR DESCRIPTION
**Pull request by johnbaldwin**
DRAFT PR to run tests on build branch with hot fix cherry pick of 

bbefd3e30a0aca97cda8fce73c56d6d12c42f2b2

### CODE REVIEW

**Comment by melvinsoft** [comment]
@johnbaldwin Maybe I'm looking wrong, but I'm not seeing this fix here: https://github.com/appsembler/figures/pull/219

I know isn't related to performance, but it would be great to bundle it in case is not.

**Comment by johnbaldwin** [comment]
@melvinsoft I only picked the critical fix needed for Tahoe prod. The other commits are specific to ginkgo or testing

**Comment by melvinsoft** [comment]
@johnbaldwin Ok, thanks! Got it.

**Comment by thraxil** [comment]
What is the status on this? It's still a Draft PR but hasn't changed in 10 days and AFAICT, 3.10 is already released.

**Comment by johnbaldwin** [comment]
@thraxil Yeah, I can get rid of this one. Thanks for the nudge

**Pull request closed without merging**
