### PR TITLE
Fixed naive datetime warnings

### PR DESCRIPTION
**Pull request by johnbaldwin**
Also did code cleanup and improve conformity

### CODE REVIEW

**Comment by johnbaldwin** [comment]
[(3) Buffer - Fix naive datetime warnings](https://trello.com/c/JFpyATos/643-3-buffer-fix-naive-datetime-warnings)

**Comment by thraxil** [comment]
Can I recommend doing a fairly large fixup like changing the quotes everywhere as a separate commit/PR from a regular code change? It adds a lot of noise and makes it harder to review.

**Comment by johnbaldwin** [comment]
@thraxil I can do that. Sorry for the noise

**Comment by johnbaldwin** [comment]
@thraxil Here's the PR with just the naive datetime fixes. Sorry for the noise and thanks for reviewing

**Comment by johnbaldwin** [comment]
Looks like i've got to add some more test coverage to make the diff pass

**Comment by johnbaldwin** [comment]
@thraxil I seem to be missing something here. From what I can tell, this diff doesn't change the test coverage but the codecov/patch is failing. Is this because there are test files changed and the total coverage of the test files is considered for the patch coverage? If so, I'd prefer not to include test coverage improvements in this PR and instead do those as a test cleanup specific PR, like I'll do a docstring specific PR at some date in the future

**Comment by johnbaldwin** [comment]
@thraxil Thank you!

**Pull request merged**
