### PR TITLE
Removed front end compiled assets

### PR DESCRIPTION
**Pull request by johnbaldwin**
Maintaining compiled front end assets is note providing real value for
the project maintenance effort

### CODE REVIEW

**Comment by melvinsoft** [comment]
@johnbaldwin Can you elaborate a little bit more here? There are some merging conflicts as well.

**Comment by johnbaldwin** [comment]
@melvinsoft When there is a PR for static assets, there is always (or almost always) a merge conflict and causes extra work to resolve. If you look at the files, you will see that all the changes and only the changes in this PR are deleting files, the compiled static assets automatically generated. Does this help explain it better?

**Comment by johnbaldwin** [comment]
@OmarIthawi You are correct. So I need to and have been planning on building the assets into the PyPI package and declare in `edx-configs` from that. What I'd prefer is to have an ansible role to compile Figures assets on deployment

**Comment by johnbaldwin** [comment]
I rebased from develop, addressed conflicts. Waiting for checks

**Comment by johnbaldwin** [comment]
@OmarIthawi @melvinsoft Would one of you please re-approve? I resolved the merge conflict

**Pull request merged**
