### PR TITLE
Cache learner course grades to improve front end performance

### PR DESCRIPTION
**Pull request by johnbaldwin**
This PR adds caching of the grades retrieved from `CourseGradeFactory` to a new Figures model, `LearnerCourseGradeMetrics`

This model aggregates a learner's gradable section progress data and significantly improves front end performance.

Updates include:

* New model, `LearnerCourseGradeMetrics` to store the aggregated gradable progress data
* Update to the pipeline to populate this model
* Update to the REST API to return data from the model instead of dynamically retrieving from mdulestore via `CourseGradeFactory`
* Minor update to the front end code to match course progress keys returned from the REST API
* Added model to the admin interface

Other additions:

* Update the devsite `settings.py` settings file so that developers can now run management commands, like `migrate` from Figures instead of having to run from the edx-platform devstack. This also moves Figures a step further to standalone dev mode
* Added PipelineError to the admin interface
* minor code cleanup

### CODE REVIEW

**Comment by johnbaldwin** [comment]
[(2) Create model to store generated grade per course enrollment](https://trello.com/c/D3FYwjLx/608-2-create-model-to-store-generated-grade-per-course-enrollment)

**Comment by johnbaldwin** [comment]
[Epic: Cache generated grades in Figures](https://trello.com/c/sNJNCn3n/591-epic-cache-generated-grades-in-figures)

**Comment by johnbaldwin** [comment]
[Review grades caching / grades metrics model](https://trello.com/c/uispoFGc/644-review-grades-caching-grades-metrics-model)

**Comment by OmarIthawi** [comment]
This is an old one. I'd like to review but I'm currently fully booked with the LTI changes @johnbaldwin. Please feel free to tag someone else.

**Pull request merged**
