### PR TITLE
Fix the comparison showing N/A when comparing to zero

### PR DESCRIPTION
**Pull request by grozdanowski**
As per title. Essentially it would check if the past value exists, however it treated 0 (zero) the same way as undefined or Null. Now fixed.

### CODE REVIEW

**Comment by johnbaldwin** [comment]
@grozdanowski You can't add the compiled assets to master. Do you need me to fix your commits?

**Review by johnbaldwin — CHANGES_REQUESTED** [review]
We need to remove compiled assets

**Comment by johnbaldwin** [comment]
I killed travis so it wouldn't be in the queue, there's no python in this PR, and the travis delays are slowing us down

**Comment by grozdanowski** [comment]
@johnbaldwin compiled assets removed.

**Review by OmarIthawi — APPROVED** [review]

**Comment by grozdanowski** [comment]
@johnbaldwin changes made, just waiting on your approval and you can merge it.

**Review by johnbaldwin — APPROVED** [review]
Thanks for removing the assets, @grozdanowski !

**Comment by johnbaldwin** [comment]
@grozdanowski I merged master in here and will merge this PR into master after the tests finish

**Pull request merged**
